name: MSBuild

# on: [workflow_dispatch]
on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Restore SFML 2.5.1
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        $url = "https://github.com/SFML/SFML/releases/download/2.5.1/SFML-2.5.1-windows-vc15-64-bit.zip"
        $zip_file = "${{env.GITHUB_WORKSPACE}}/" + $(Split-Path -Path $url -Leaf)
        $unzip_folder = "${{env.GITHUB_WORKSPACE}}/"
        Invoke-WebRequest -Uri $url -OutFile $zip_file
        Expand-Archive -Path $zip_file -DestinationPath $unzip_folder

    - name: Build All
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Platform=${{env.BUILD_PLATFORM}} /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
     
    - name: Test All
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
         $files = Get-ChildItem -Filter ${{env.SOLUTION_FILE_PATH}}\${{env.BUILD_PLATFORM}}\${{env.BUILD_CONFIGURATION}}\lesson.*.test.exe 
         foreach ($file in $files) {
            Write-Output "Run: $($file.FullName)"
            & $file.FullName
            if(-not $?) {
                Exit $LASTEXITCODE
            }
         } 